export const STATES = [
    'maharashtra',
	'jammu and kashmir',
	'uttar pradesh',
	'uttar pradesh',
	'gujarat',
	'andhra pradesh',
	'gujarat',
	'karnataka',
	'andhra pradesh',
	'kerala',
	'karnataka',
	'west bengal',
	'karnataka',
	'tripura',
	'uttar pradesh',
	'chhattisgarh',
	'gujarat',
	'punjab',
	'maharashtra',
	'maharashtra',
	'mizoram',
	'rajasthan',
	'maharashtra',
	'chhattisgarh',
	'kerala',
	'jammu and kashmir',
	'maharashtra',
	'maharashtra',
	'maharashtra',
	'karnataka',
	'maharashtra',
	'gujarat',
	'kerala',
	'goa',
	'maharashtra',
	'uttar pradesh',
	'west bengal',
	'uttar pradesh',
	'uttarakhand',
	'karnataka',
	'arunachal pradesh',
	'karnataka',
	'rajasthan',
	'andhra pradesh',
	'andhra pradesh',
	'maharashtra',
	'bihar',
	'maharashtra',
 	'chhattisgarh',
	'gujarat',
	'gujarat',
	'maharashtra',
	'karnataka',
	'chhattisgarh',
  	'maharashtra',
	'assam',
	'lakshadweep',
	'jharkhand',
]